main/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.home,name='home'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('save-comment',views.save_comment,name='save-comment'),
    path('save-upvote',views.save_upvote,name='save-upvote'),
    path('save-downvote',views.save_downvote,name='save-downvote'),
    # User Register
    path('accounts/register/',views.register,name='register'),
    # Profile
    path('accounts/profile/',views.profile,name='profile'),
    # Ask QUestion
    path('ask-question',views.ask_form,name='ask-question'),
    # Tag Page
    path('tag/<str:tag>',views.tag,name='tag'),
    # Tags Page
    path('tags',views.tags,name='tags'),
]

questans/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Custom User Model
class CustomUser(AbstractUser):
    bio=models.TextField()
    location=models.CharField(max_length=200)


# Question Model
class Question(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    detail=models.TextField()
    tags=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# Answer Model
class Answer(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.detail

# Comment
class Comment(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='comment_user')
    comment=models.TextField(default='')
    add_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

# UpVotes
class UpVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='upvote_user')

# DownVotes
class DownVote(models.Model):
    answer=models.ForeignKey(Answer,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE,related_name='downvote_user')

main/forms.py
from dataclasses import fields
from pyexpat import model
from tkinter import Widget
from click import style
from django import forms
from django.forms import ModelForm, TextInput
from .models import Answer,Question,CustomUser


class AnswerForm(ModelForm):
    class Meta:
        model=Answer
        fields=('detail',)
        widgets={
            'detail': TextInput(attrs={
                'class':'form-control',
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Write here...',

            }),
        }

class QuestionForm(ModelForm):
    class Meta:
        model=Question
        fields=('title','detail','tags')
        widgets={
            'title': TextInput(attrs={
                'class':'form-control',
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Title...'

            }),
            'detail': TextInput(attrs={
                'class': "form-control",
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Details...'
            }),
            'tags':TextInput(attrs={
                'class': "form-control",
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Tags...'
            })
        }

class ProfileForm(ModelForm):
    class Meta:
        model=CustomUser
        fields=('first_name','last_name','username','bio','location')
        widgets={
            'first_name': TextInput(attrs={
                'class':'form-control',
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'First Name...'

            }),
            'last_name': TextInput(attrs={
                'class': "form-control",
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Last Name...'
            }),
            'username':TextInput(attrs={
                'class': "form-control",
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Username...',
                
            }),
            'bio':TextInput(attrs={
                'class': "form-control",
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Bio...',
                
            }),
            'location':TextInput(attrs={
                'class': "form-control",
                'style':'background-color:#202124; color:white; border-color:black;',
                'placeholder':'Location...',
                
            })
        }

main/views.py
from imaplib import _Authenticator
from multiprocessing import AuthenticationError
from tkinter import Widget
from click import style
from django import forms
from django.shortcuts import render,HttpResponse
from django.http import JsonResponse
from .models import Question,Answer,Comment,UpVote,DownVote
from django.core.paginator import Paginator
from django.contrib import messages
from .forms import AnswerForm,QuestionForm,ProfileForm
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count


from main import forms
# Home Page
def home(request):
    if 'q' in request.GET:
        q=request.GET['q']
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(title__icontains=q).order_by('-id')
    else:
        quests=Question.objects.annotate(total_comments=Count('answer__comment')).all().order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'home.html',{'quests':quests})

# Detail
def detail(request,id):
    quest=Question.objects.get(pk=id)
    tags=quest.tags.split(',')
    answers=Answer.objects.filter(question=quest)
    answerform=AnswerForm
    if request.method=='POST':
        answerData=AnswerForm(request.POST)
        if answerData.is_valid():
            answer=answerData.save(commit=False)
            answer.question=quest
            answer.user=request.user
            answer.save()
            messages.success(request,'Answer has been submitted.')
    return render(request,'detail.html',{
        'quest':quest,
        'tags':tags,
        'answers':answers,
        'answerform':answerform
    })

# Save Comment
def save_comment(request):
    if request.method=='POST':
        comment=request.POST['comment']
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        Comment.objects.create(
            answer=answer,
            comment=comment,
            user=user
        )
        return JsonResponse({'bool':True})

# Save Upvote
def save_upvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=UpVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            UpVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})

# Save Downvote
def save_downvote(request):
    if request.method=='POST':
        answerid=request.POST['answerid']
        answer=Answer.objects.get(pk=answerid)
        user=request.user
        check=DownVote.objects.filter(answer=answer,user=user).count()
        if check > 0:
            return JsonResponse({'bool':False})
        else:
            DownVote.objects.create(
                answer=answer,
                user=user
            )
            return JsonResponse({'bool':True})

# User Register
def register(request):
    form=UserCreationForm
    if request.method=='POST':
        regForm=UserCreationForm(request.POST)
        if regForm.is_valid():
            regForm.save()
            messages.success(request,'User has been registered!!')
    return render(request,'registration/register.html',{'form':form})



# Ask Form
def ask_form(request):
    form=QuestionForm
    if request.method=='POST':
        questForm=QuestionForm(request.POST)
        if questForm.is_valid():
            questForm=questForm.save(commit=False)
            questForm.user=request.user
            questForm.save()
            messages.success(request,'Question has been added.')
    return render(request,'ask-question.html',{'form':form})


# Questions according to tag
def tag(request,tag):
    quests=Question.objects.annotate(total_comments=Count('answer__comment')).filter(tags__icontains=tag).order_by('-id')
    paginator=Paginator(quests,10)
    page_num=request.GET.get('page',1)
    quests=paginator.page(page_num)
    return render(request,'tag.html',{'quests':quests,'tag':tag})

# Profile
def profile(request):
    quests=Question.objects.filter(user=request.user).order_by('-id')
    answers=Answer.objects.filter(user=request.user).order_by('-id')
    comments=Comment.objects.filter(user=request.user).order_by('-id')
    upvotes=UpVote.objects.filter(user=request.user).order_by('-id')
    downvotes=DownVote.objects.filter(user=request.user).order_by('-id')
    if request.method=='POST':
        profileForm=ProfileForm(request.POST,instance=request.user)
        if profileForm.is_valid():
            profileForm.save()
            messages.success(request,'Profile has been updated.')
    form=ProfileForm(instance=request.user)
    return render(request,'registration/profile.html',{
        'form':form,
        'quests':quests,
        'answers':answers,
        'comments':comments,
        'upvotes':upvotes,
        'downvotes':downvotes,
    })

# Tags Page
def tags(request):
    quests=Question.objects.all()
    tags=[]
    for quest in quests:
        qtags=[tag.strip() for tag in quest.tags.split(',')]
        for tag in qtags:
            if tag not in tags:
                tags.append(tag)
    # Fetch Questions
    tag_with_count=[]
    for tag in tags:
        tag_data={
            'name':tag,
            'count':Question.objects.filter(tags__icontains=tag).count()
        }
        tag_with_count.append(tag_data)
    return render(request,'tags.html',{'tags':tag_with_count})
        
        

main/templates/ask-question.html
{% extends 'base.html' %}
{% block title %}Ask Question{% endblock %}
{% block activeAsk %}active{% endblock %}
{% block content %}
<div class="container">
    <div class="card mt-5" style="border-radius:0px 40px 0px 40px;background-color:#202124">
        <h5 class="card-header" style="font-size:30px;color:white"><b>Ask Question<b></h5>
        <div class="card-body">
            {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
            {% endfor %}
            <form method="post">
                {% csrf_token %}
                <table class="table table-dark" style="color:white;">
                    {{form.as_table}}
                    <tr>
                        <td colspan="2">
                            <button class="btn btn-dark" style="background-color:#202124">Submit</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}{{quest.title}}{% endblock %}
{% block content %}
<!-- Question List -->
    <div class="container">
        <h2 class="my-4" style="color:white; font-size:26px;font-weight:bold">{{quest.title}}</h2>
        <p style="color:white">{{quest.detail}}</p>
        <p style="color:white">
            tags:
            {% for tag in tags %}
            <a href="/tag/{{tag|slugify}}" class="badge badge-secondary p-1">{{tag}}</a>
            {% endfor %}
        </p>
        
        <p style="color:white">
            <span class="mr-4">{{quest.add_time|date:'d/m/Y'}}</span>
            <a href="#" style="color:#00BFFF">@{{quest.user.username}}</a>
        </p>
        <hr/>
        {% for answer in answers %}
        <div class="row" style="color:white">
            <div class="col-1" style="text-align: center;">
                <div class="upvote">
                    <strong class="upvote-count-{{answer.id}}">{{answer.upvote_set.count}}</strong><br/>
                    <span class="text-success">
                        <i class="fa fa-arrow-up fa-2x upvote-click" data-answer="{{answer.id}}"></i>
                    </span>
                </div>
                <div class="downvote mt-3">
                    <span class="text-danger">
                        <i class="fa fa-arrow-down fa-2x downvote-click" data-answer="{{answer.id}}"></i>
                    </span><br/>
                    <strong class="downvote-count-{{answer.id}}">{{answer.downvote_set.count}}</strong>
                </div>
            </div>
            <div class="col-11" >
                <p>
                    {{ answer.detail }}
                </p>
                <p >
                    <a href="#" class="mr-3" style="color:#00BFFF">@{{answer.user.username}}</a>
                    <span class="mr-3"><span class="comment-count-{{answer.id}}">{{answer.comment_set.count}}</span> comments</span>
                    <span>{{answer.add_time|date:'d/m/Y h:i:s'}}</span>
                </p>
                <!-- Comment Section Start -->
                <h3 class="my-4" style="color:white">Comment</h3>
                <div class="comment-wrapper-{{answer.id}}" >
                    {% for comment in answer.comment_set.all %}
                    <div class="card mb-2"  style="background-color:#202124;border-radius:0px 30px 0px 30px">
                        <div class="card-body"  style="background-color:#202124;border-radius:0px 30px 0px 30px">
                            <p>{{comment.comment}}</p>
                            <p> <a href="#" style="color:#00BFFF">@{{comment.user.username}}</a>
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if user.is_authenticated %}
                <!-- Comment Form -->
                <div class="card my-3" style="background-color:#202124;border-radius:0px 30px 0px 30px">
                    <h6 class="card-header" >Add Comment</h6>
                    <div class="card-body">
                        <textarea class="form-control comment-text-{{answer.id}}" style='background-color:#202124; color:white; border-color:black;'></textarea>
                        <button type="button" data-answer="{{answer.id}}" class="btn btn-dark my-3 save-comment">Submit</button>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        <hr/>
        {% endfor %}

        {% if user.is_authenticated %}
        {% for msg in messages %}
            <p class="text-success">{{msg}}</p>
        {% endfor %}
        <form method="post" >
            {% csrf_token %}
            <table class="table table-dark" style="background-color:#202124; border-radius:0px 20px 0px 20px">
                {{answerform.as_table}}
                <tr>
                    <td colspan="2">
                        <input type="submit" class="btn btn-dark" />
                    </td>
                </tr>
            </table>
        </form>
        {% endif %}
    </div>
<script>
    $(document).ready(function(){
        $(".save-comment").on('click',function(){
            var _answerid=$(this).data('answer');
            var _comment=$(".comment-text-"+_answerid).val();
            // Ajax
            $.ajax({
                url:"/save-comment",
                type:"post",
                data:{
                    comment:_comment,
                    answerid:_answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                beforeSend:function(){
                    $(".save-comment").addClass('disabled').text('saving...');
                },
                success:function(res){
                    if(res.bool==true){
                        $(".comment-text-"+_answerid).val('');
                        // Append Element
                        var _html='<div class="card mb-2 animate__animated animate__bounce">\
                        <div class="card-body">\
                            <p>'+_comment+'</p>\
                            <p>\
                                <a href="#">{{request.user}}</a>\
                            </p>\
                        </div>\
                    </div>';
                    $(".comment-wrapper-"+_answerid).append(_html);
                    var prevCount=$(".comment-count-"+_answerid).text();
                    $(".comment-count-"+_answerid).text(parseInt(prevCount)+1);
                    }
                    $(".save-comment").removeClass('disabled').text('Submit');
                }
            });
        });

        // Upvote
        $(".upvote-click").on('click',function(){
            var answerid=$(this).data('answer');
            // Ajax
            $.ajax({
                url:"/save-upvote",
                type:"post",
                data:{
                    answerid:answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".upvote-count-"+answerid).text();
                    if(res.bool==true){
                        $(".upvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });

        // Downvote
        $(".downvote-click").on('click',function(){
            var answerid=$(this).data('answer');
            // Ajax
            $.ajax({
                url:"/save-downvote",
                type:"post",
                data:{
                    answerid:answerid,
                    csrfmiddlewaretoken:"{{csrf_token}}"
                },
                dataType:'json',
                success:function(res){
                    var _prevupvote=$(".downvote-count-"+answerid).text();
                    if(res.bool==true){
                        $(".downvote-count-"+answerid).text(parseInt(_prevupvote)+1);
                    }
                }
            });
        });
    });
</script>
{% endblock %}

main/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | AurKoiSawal</title>
    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body style="background-color: #353535;">
    <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #151515" >
        <div class="container"><!-- nav-tabs-->
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-20 h-20 text-white p-2  rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <a class="navbar-brand" href="#" ><p style="color: white; font-size: 40px; margin: 10px;font-weight:bold; font-family: 'Times New Roman', serif;">Aur Koi Sawal<p></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNav">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item active" >
                        <a class="nav-link" href="#" style="font-size:30px; ">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/tags" style="font-size:30px;">Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ask-question" style="font-size:30px;">Ask</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/profile" style="font-size:30px;">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}" style="font-size:30px;">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login" style="font-size:30px;">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/register" style="font-size:30px;">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Search Section -->
    <div class="container py-5">
        <div class="row">
            <div class="col-md-8 offset-2">
                <form>
                    <div class="input-group">
                        <input type="text" name="q" class="form-control form-control-lg" placeholder="Search here...!" style="border-radius: 0px 0px 0px 20px; border-color: #202124;"/>
                        <div class="input-group-append">
                        <button class="btn btn-dark" type="submit" id="button-addon2" style="background-color:#202124; border-radius: 0px 20px 0px 0px; margin-left:10px;">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    
    <!-- Question List -->
    <div class="container" >
        {% for quest in quests %}
        <div class="card mb-4 shadow" style="background-color: #202124; border-radius: 0px 30px 0px 30px">
            <div class="card-body">
                <h4 class="card-title"><a href="/detail/{{quest.id}}" style="color:white; font-size:20px;"><b>{{quest.title}}</b></a></h4>
                <p class="card-text" style="color:white">{{quest.detail}}</p>
                <p>
                    <a href="#" class="mr-2" style="color:#00BFFF">@{{quest.user.username}}</a>
                    <a href="#" class="mr-2" style="color:white">{{quest.answer_set.count}} Answers</a>
                    <a href="#" class="mr-2" style="color:white">{{quest.total_comments}} Comments</a>
                </p>
            </div>
            <div class="card-footer">
                <small style="color:white">{{quest.add_time}}</small>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if quests.has_other_pages %}
    <!-- Pagination -->
    <nav class="my-3 container">
        <ul class="pagination">
            {% if quests.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{quests.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in quests.paginator.page_range %}
          {% if quests.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
          {% endif %}
          {% endfor %}
          {% if quests.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{quests.next_page_number}}">Next</a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
    <!-- Footer -->
    <footer class="text-gray-600 body-font" style="background-color: #151515">
        <div class="container px-5 py-24 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
          <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
            <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-20 h-20 text-white p-2  rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
              </svg>
              <span class="ml-3 text-xl" style="color:white;font-size:24px; font-family: 'Times New Roman', serif; font-weight:bold">Aur Koi Sawal</span>
            </a>
          </div>
          <div class="flex-grow flex flex-wrap md:pl-20 -mb-10 md:mt-0 mt-10 md:text-left text-center">
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3" style="color:white;">STACK OVERFLOW</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Question</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Help</a>
                </li>
                
              </nav>
            </div>
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3" style="color:white;">PRODUCTS</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Teams</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Advertising</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Collectives</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Talent</a>
                </li>
              </nav>
            </div>
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3" style="color:white;">COMPANY</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">About</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Press</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Work Here</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Legal</a>
                </li>
                <li>
                    <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Privacy Policy</a>
                  </li>
                  
              </nav>
            </div>
            <div class="lg:w-1/4 md:w-1/2 w-full px-4">
              <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3" style="color:white;">STACK EXCHANGE NETWORK</h2>
              <nav class="list-none mb-10">
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Technology</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Culture & recreation</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Life & arts</a>
                </li>
                <li>
                  <a class="text-gray-600 hover:text-gray-800" style="color:gray;">Science</a>
                </li>
              </nav>
            </div>
          </div>
        </div>
        <div class="bg-white-100">
          <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
            <p class="text-gray-500 text-sm text-center sm:text-left">© 2020 AurKoiSawal —
              <a href="https://twitter.com/PankajS90177959" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">@PankajS90177959</a>
            </p>
            <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
              <a class="text-gray-500" href="https://www.facebook.com/">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                </svg>
              </a>
              <a class="ml-3 text-gray-500" href="https://twitter.com/">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                </svg>
              </a>
              <a class="ml-3 text-gray-500" href="https://www.instagram.com/">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                </svg>
              </a>
              <a class="ml-3 text-gray-500" href="https://www.linkedin.com/">
                <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
                  <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
                  <circle cx="4" cy="4" r="2" stroke="none"></circle>
                </svg>
              </a>
            </span>
          </div>
        </div>
      </footer>
</body>
</html>